name: B4Purpose
favicon: null
layout_spectrum: 0.7420105894561857
typography_spectrum: 0.8954231520183384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1482052847277373
  lightness: 0.186920226784423
  saturation: 0.6335246511735022
  rhythmicContrast: 0.2608206004370004
purpose: []
